// ============================================================================
// Neon Grid / Web — baked-in mock dataset. Self-contained, deterministic.
// Every page renders fully populated from this object. No fetch, no SSE.
// Exposed as window.NG_DATA (global, non-module).
// ============================================================================
window.NG_DATA = (function(){
  const NOW = '2026-07-20T17:42:00Z';
  // helper for building ISO timestamps behind NOW (deterministic)
  const ago = (mins) => new Date(Date.parse(NOW) - mins * 60000).toISOString();

  // ---- neon spectrum (mirror of design tokens) ----
  const C = { cyan:'#00E0FF', green:'#00FF95', fuchsia:'#FF2DAA', orange:'#FF9500',
              blue:'#1F9BFF', violet:'#8A45FF', red:'#FF3B5C', yellow:'#FFE11A', dim:'#62749C' };

  // ===================== FINDINGS (22) =====================
  // done = resolved|verified|wont_fix ; active = open|in_progress
  const findings = [
    { id:1, slug:'v8-thumb-interwork-crash', title:'ARM/Thumb interworking veneer corrupts LR on deopt', severity:'critical', status:'open', phase:'boot', subsystem:'v8-arm', subsystem_detail:'codegen/arm', effort:'L', risk:'Renderer hard-crash on any deopt path', confidence:'high', location:'v8/src/codegen/arm/macro-assembler-arm.cc:2184', evidence:'BLX to a Thumb stub returns with bit0 clear; LR points mid-instruction, faults at 0x?????? on first GC after deopt.', recommendation:'Emit interworking-safe veneer; assert bit0 on all BLX targets in debug.', workflow:'crash-triage', source:'device-dump', category:'correctness', device_impact:'fatal', created_at:ago(4320), updated_at:ago(190), resolved_at:null },
    { id:2, slug:'skia-neon-alpha-banding', title:'NEON alpha-blend fast path banding on gradients', severity:'high', status:'in_progress', phase:'gpu', subsystem:'skia-neon', subsystem_detail:'blitter/neon', effort:'M', risk:'Visible banding on every gradient fill', confidence:'high', location:'skia/src/opts/SkBlitRow_opts_arm_neon.cpp:412', evidence:'vshr rounding drops 3 low bits; 8-bit gradients quantize to 5 bits. Diff vs C path attached.', recommendation:'Use vrshrn (rounding) and widen accumulator to 16-bit.', workflow:'perf-hotpath', source:'pixel-diff', category:'correctness', perf_mechanism:'simd', created_at:ago(2880), updated_at:ago(95), resolved_at:null },
    { id:3, slug:'tegra-gl-context-loss', title:'Tegra 4 GL context lost on tab background -> black compositor', severity:'critical', status:'open', phase:'gpu', subsystem:'gpu-tegra', subsystem_detail:'egl/context', effort:'XL', risk:'All GPU tabs go black; requires restart', confidence:'medium', location:'gpu/command_buffer/service/gles2_cmd_decoder.cc:9931', evidence:'EGL_CONTEXT_LOST after ~40s backgrounded; Tegra driver drops share group; no robustness ext.', recommendation:'Detect loss, tear down + rebuild share group, replay resources.', workflow:'crash-triage', source:'device-dump', category:'correctness', device_impact:'severe', created_at:ago(3600), updated_at:ago(60), resolved_at:null },
    { id:4, slug:'partition-alloc-oom-2g', title:'PartitionAlloc address-space exhaustion under 2GB user VA', severity:'high', status:'open', phase:'perf', subsystem:'mem-partition', subsystem_detail:'partition_alloc', effort:'L', risk:'OOM crash on media-heavy pages', confidence:'high', location:'base/allocator/partition_allocator/partition_root.cc:1502', evidence:'Win8.1 RT gives 2GB user VA; super-page reservation fragments; alloc fails at ~1.4GB RSS.', recommendation:'Shrink super-page to 1MB on 32-bit; enable decommit-on-empty.', workflow:'perf-hotpath', source:'profiler', category:'resource', perf_mechanism:'memory', created_at:ago(2600), updated_at:ago(240), resolved_at:null },
    { id:5, slug:'tls13-schannel-handshake', title:'TLS 1.3 handshake fails via legacy Schannel on 8.1', severity:'high', status:'resolved', phase:'boot', subsystem:'net-tls', subsystem_detail:'ssl/schannel', effort:'M', risk:'No HTTPS to TLS1.3-only hosts', confidence:'high', location:'net/socket/ssl_client_socket_impl.cc:640', evidence:'Schannel on 8.1 lacks TLS1.3; BoringSSL path was gated off for ARM32.', recommendation:'Force BoringSSL for ARM32 build; drop Schannel fallback.', workflow:'compat-shim', source:'code-review', category:'compat', resolution:'Enabled BoringSSL unconditionally for arm32; verified handshake to Cloudflare.', created_at:ago(5400), updated_at:ago(1300), resolved_at:ago(1300) },
    { id:6, slug:'mojo-ipc-32b-offset', title:'Mojo message header 32-bit offset truncates large payloads', severity:'medium', status:'in_progress', phase:'boot', subsystem:'ipc-mojo', subsystem_detail:'core/message', effort:'M', risk:'Corrupt IPC on >4GB cumulative offset', confidence:'medium', location:'mojo/core/message.cc:288', evidence:'size_t assumed 64-bit; on ARM32 it is 32-bit; offset math wraps for large handle tables.', recommendation:'Use explicit uint64_t for payload offsets.', workflow:'bringup', source:'code-review', category:'correctness', created_at:ago(2200), updated_at:ago(150), resolved_at:null },
    { id:7, slug:'views-dpi-scale-blur', title:'Non-integer DPI scale blurs Views UI on Surface 2 RT', severity:'low', status:'open', phase:'polish', subsystem:'ui-views', subsystem_detail:'compositor/dsf', effort:'S', risk:'Slightly soft UI at 1.5x', confidence:'high', location:'ui/views/view.cc:1120', evidence:'1.5 DSF rounds layer bounds down; text snaps off pixel grid.', recommendation:'Round bounds to enclosing pixel rect.', workflow:'cleanup', source:'visual-qa', category:'polish', device_impact:'cosmetic', created_at:ago(1500), updated_at:ago(400), resolved_at:null },
    { id:8, slug:'ffmpeg-neon-h264-artifact', title:'FFmpeg NEON H.264 IDCT produces green macroblocks', severity:'high', status:'open', phase:'gpu', subsystem:'media-ffmpeg', subsystem_detail:'h264/idct_neon', effort:'L', risk:'Corrupt video playback', confidence:'medium', location:'third_party/ffmpeg/libavcodec/arm/h264idct_neon.S:96', evidence:'Saturating add overflows on high-freq coeffs; green blocks at scene cuts.', recommendation:'Fix vqadd operand widths; add fate ref for arm32.', workflow:'perf-hotpath', source:'pixel-diff', category:'correctness', perf_mechanism:'simd', created_at:ago(2400), updated_at:ago(300), resolved_at:null },
    { id:9, slug:'thread-affinity-tegra4', title:'Thread affinity ignores Tegra 4 companion core', severity:'medium', status:'verified', phase:'perf', subsystem:'base-threading', subsystem_detail:'task/thread_pool', effort:'M', risk:'Wasted 5th core / worse battery', confidence:'high', location:'base/task/thread_pool/thread_group.cc:410', evidence:'4-PLUS-1 topology; companion core never scheduled for background pool.', recommendation:'Pin background pool to companion core when idle.', workflow:'perf-hotpath', source:'profiler', category:'performance', perf_mechanism:'scheduling', resolution:'Background pool now targets companion core; 11% idle-power win, verified on device.', created_at:ago(3000), updated_at:ago(700), resolved_at:ago(700) },
    { id:10, slug:'disk-cache-index-corrupt', title:'Disk cache index v3 corrupts on unclean shutdown', severity:'critical', status:'open', phase:'stability', subsystem:'storage-disk-cache', subsystem_detail:'simple_cache/index', effort:'L', risk:'Cache wipe + crash loop on next boot', confidence:'medium', location:'net/disk_cache/simple/simple_index_file.cc:520', evidence:'Index fsync skipped on RT; power-loss leaves half-written index; loader crashes.', recommendation:'Write index to temp + atomic rename; validate CRC on load.', workflow:'crash-triage', source:'device-dump', category:'correctness', device_impact:'severe', created_at:ago(1800), updated_at:ago(120), resolved_at:null },
    { id:11, slug:'sandbox-win81-token', title:'Renderer sandbox token too permissive on Win 8.1', severity:'high', status:'deferred', phase:'polish', subsystem:'sandbox-win', subsystem_detail:'win/restricted_token', effort:'L', risk:'Weaker renderer isolation', confidence:'medium', location:'sandbox/win/src/restricted_token_utils.cc:210', evidence:'AppContainer unavailable on 8.1; falls back to lowbox with extra caps.', recommendation:'Tighten lowbox capability set; audit against 8.1 baseline.', workflow:'security-audit', source:'code-review', category:'security', resolution:'Deferred to post-bringup security pass.', created_at:ago(2100), updated_at:ago(900), resolved_at:null },
    { id:12, slug:'angle-d3d9-shader-fallback', title:'ANGLE D3D9 fallback drops ESSL3 shaders silently', severity:'medium', status:'in_progress', phase:'gpu', subsystem:'gl-angle', subsystem_detail:'d3d9/translator', effort:'M', risk:'Some WebGL2 sites render blank', confidence:'high', location:'third_party/angle/src/libANGLE/renderer/d3d/d3d9/Renderer9.cpp:1830', evidence:'Tegra exposes FL9_3; ESSL3 shaders rejected with no console warning.', recommendation:'Emit GL_INVALID_OPERATION + devtools warning; document FL9_3 limits.', workflow:'compat-shim', source:'code-review', category:'compat', created_at:ago(1700), updated_at:ago(180), resolved_at:null },
    { id:13, slug:'v8-jit-cache-flush-miss', title:'V8 code cache misses ARM icache flush after relocation', severity:'high', status:'open', phase:'perf', subsystem:'v8-arm', subsystem_detail:'codegen/flush', effort:'M', risk:'Rare stale-code execution -> crash', confidence:'medium', location:'v8/src/codegen/arm/cpu-arm.cc:44', evidence:'FlushICache range off-by-page after code-space compaction; Tegra icache stale.', recommendation:'Flush full moved range incl. trailing page.', workflow:'perf-hotpath', source:'device-dump', category:'correctness', perf_mechanism:'cpu-cache', created_at:ago(1400), updated_at:ago(210), resolved_at:null },
    { id:14, slug:'startup-splash-race', title:'Startup splash races GPU init -> white flash', severity:'low', status:'resolved', phase:'boot', subsystem:'ui-views', subsystem_detail:'startup/splash', effort:'S', risk:'Cosmetic white flash on cold boot', confidence:'high', location:'chrome/browser/ui/startup/startup_browser_creator.cc:980', evidence:'Splash shown before compositor ready; one-frame white flash.', recommendation:'Gate splash on first compositor frame.', workflow:'bringup', source:'visual-qa', category:'polish', resolution:'Splash now waits for first frame; flash gone.', device_impact:'cosmetic', created_at:ago(4600), updated_at:ago(1600), resolved_at:ago(1600) },
    { id:15, slug:'gc-pause-spike-scroll', title:'V8 GC pause spikes to 90ms during fling scroll', severity:'medium', status:'open', phase:'perf', subsystem:'v8-arm', subsystem_detail:'heap/incremental', effort:'M', risk:'Janky scrolling', confidence:'high', location:'v8/src/heap/incremental-marking.cc:701', evidence:'Incremental step budget too large for 1.4GHz A15; 90ms major-GC pause mid-fling.', recommendation:'Scale step size by measured mutator speed.', workflow:'perf-hotpath', source:'profiler', category:'performance', perf_mechanism:'gc', created_at:ago(1200), updated_at:ago(260), resolved_at:null },
    { id:16, slug:'font-fallback-cjk-missing', title:'CJK fallback font not bundled -> tofu', severity:'low', status:'open', phase:'polish', subsystem:'skia-neon', subsystem_detail:'fonts/fallback', effort:'S', risk:'Tofu boxes on CJK pages', confidence:'high', location:'ui/gfx/font_fallback_win.cc:150', evidence:'RT image lacks Yu Gothic; no bundled CJK fallback.', recommendation:'Bundle Noto Sans CJK subset.', workflow:'cleanup', source:'visual-qa', category:'polish', device_impact:'cosmetic', created_at:ago(1100), updated_at:ago(500), resolved_at:null },
    { id:17, slug:'net-proxy-resolver-hang', title:'PAC proxy resolver hangs V8 isolate on 8.1 WPAD', severity:'high', status:'open', phase:'stability', subsystem:'net-tls', subsystem_detail:'proxy/pac', effort:'M', risk:'Network stall / apparent freeze', confidence:'medium', location:'net/proxy_resolution/proxy_resolver_v8.cc:390', evidence:'WPAD DNS on 8.1 blocks; PAC isolate never yields; net thread stuck 20s.', recommendation:'Time-box PAC eval; async WPAD.', workflow:'crash-triage', source:'device-dump', category:'correctness', device_impact:'severe', created_at:ago(900), updated_at:ago(140), resolved_at:null },
    { id:18, slug:'dead-flag-legacy-gpu', title:'Dead --disable-legacy-gpu flag left in switches', severity:'cleanup', status:'wont_fix', phase:'polish', subsystem:'gl-angle', subsystem_detail:'switches', effort:'S', risk:'None (dead code)', confidence:'high', location:'gpu/config/gpu_switches.cc:60', evidence:'Flag references a removed code path; no-op since M?.', recommendation:'Remove switch + docs.', workflow:'cleanup', source:'code-review', category:'cleanup', feature_serves_no_purpose:true, resolution:'Left in place to avoid churn in a shared file this cycle.', created_at:ago(800), updated_at:ago(600), resolved_at:ago(600) },
    { id:19, slug:'mojo-handle-leak', title:'Mojo handle leak on renderer fast-shutdown', severity:'medium', status:'in_progress', phase:'stability', subsystem:'ipc-mojo', subsystem_detail:'core/handle_table', effort:'M', risk:'FD exhaustion after many tab closes', confidence:'medium', location:'mojo/core/handle_table.cc:120', evidence:'Fast-shutdown skips handle close; table grows ~30 handles/tab-close.', recommendation:'Close handles in shutdown observer.', workflow:'crash-triage', source:'profiler', category:'resource', perf_mechanism:'memory', created_at:ago(700), updated_at:ago(170), resolved_at:null },
    { id:20, slug:'toolchain-neon-flag-missing', title:'Build missing -mfpu=neon on third_party targets', severity:'high', status:'verified', phase:'toolchain', subsystem:'v8-arm', subsystem_detail:'gn/config', effort:'S', risk:'Scalar fallback, 2-3x slower media', confidence:'high', location:'build/config/arm.gni:70', evidence:'arm_fpu default not propagated to some third_party gn configs; NEON codegen off.', recommendation:'Set arm_fpu=neon globally; assert in build.', workflow:'bringup', source:'code-review', category:'performance', resolution:'NEON enabled build-wide; verified with objdump vfp/neon opcodes.', perf_mechanism:'simd', created_at:ago(6200), updated_at:ago(5000), resolved_at:ago(5000) },
    { id:21, slug:'baseline-symbol-map', title:'Baseline symbol map + crash-key groundwork', severity:'cleanup', status:'verified', phase:'recon', subsystem:'base-threading', subsystem_detail:'crash/symbols', effort:'S', risk:'None', confidence:'high', location:'build/symbols/arm32.map', evidence:'Established symbol upload + crash keys for the ARM32 tree.', recommendation:'Keep map fresh per build.', workflow:'bringup', source:'code-review', category:'infra', resolution:'Symbol pipeline live; dumps now symbolized.', created_at:ago(7000), updated_at:ago(6500), resolved_at:ago(6500) },
    { id:22, slug:'media-eme-widevine-stub', title:'Widevine EME stubbed; DRM playback unsupported', severity:'medium', status:'deferred', phase:'polish', subsystem:'media-ffmpeg', subsystem_detail:'eme/widevine', effort:'L', risk:'No Netflix-class DRM', confidence:'high', location:'components/cdm/renderer/widevine_key_systems.cc:80', evidence:'No ARM32 Widevine CDM binary; EME returns not-supported.', recommendation:'Track upstream CDM availability; ship without DRM for now.', workflow:'compat-shim', source:'product', category:'compat', resolution:'Deferred — no ARM32 CDM exists upstream.', created_at:ago(2000), updated_at:ago(1000), resolved_at:null },
  ];

  // ===================== STATS (derived, baked) =====================
  const stats = {
    total: 22, open_active: 14, high_open: 8,
    by_severity: { critical:3, high:8, medium:6, low:3, cleanup:2 },
    by_status:   { open:10, in_progress:4, resolved:2, verified:3, wont_fix:1, deferred:2 },
    by_workflow: { bringup:4, 'perf-hotpath':6, 'crash-triage':5, cleanup:3, 'compat-shim':3, 'security-audit':1 },
    by_subsystem:{ 'v8-arm':4, 'net-tls':2, 'skia-neon':2, 'ipc-mojo':2, 'ui-views':2, 'media-ffmpeg':2, 'base-threading':2, 'gl-angle':2, 'gpu-tegra':1, 'mem-partition':1, 'storage-disk-cache':1, 'sandbox-win':1 },
    recent: [
      { id:'r1', finding_id:1,  slug:'v8-thumb-interwork-crash', title:'ARM/Thumb interworking veneer corrupts LR on deopt', field:'status', old_value:'in_progress', new_value:'open', actor:'agent', ts:ago(190), note:'Reopened — deopt repro still faults after veneer patch.' },
      { id:'r2', finding_id:3,  slug:'tegra-gl-context-loss', title:'Tegra 4 GL context lost on tab background', field:'severity', old_value:'high', new_value:'critical', actor:'user', ts:ago(60), note:'Escalated: whole compositor goes black.' },
      { id:'r3', finding_id:9,  slug:'thread-affinity-tegra4', title:'Thread affinity ignores companion core', field:'status', old_value:'resolved', new_value:'verified', actor:'user', ts:ago(700), note:'11% idle-power win confirmed on device.' },
      { id:'r4', finding_id:13, slug:'v8-jit-cache-flush-miss', title:'V8 code cache misses ARM icache flush', field:'created', old_value:'', new_value:'open', actor:'agent', ts:ago(1400), note:'Filed from device dump 0x c0000005.' },
      { id:'r5', finding_id:5,  slug:'tls13-schannel-handshake', title:'TLS 1.3 handshake fails via legacy Schannel', field:'status', old_value:'in_progress', new_value:'resolved', actor:'agent', ts:ago(1300), note:'BoringSSL forced for arm32.' },
      { id:'r6', finding_id:2,  slug:'skia-neon-alpha-banding', title:'NEON alpha-blend banding on gradients', field:'status', old_value:'open', new_value:'in_progress', actor:'agent', ts:ago(95), note:'Switching to rounding shift.' },
    ],
  };

  // ===================== PHASES (7) =====================
  const phases = [
    { key:'recon', name:'Recon & Baseline', tagline:'Map the target', goal:'Stand up the ARM32 tree, symbols, and a crash baseline.', color:C.cyan, icon:'ph-magnifying-glass', status:'done', pct:100, ordinal:0, rollup:{ total:1, done:1, open_crit_high:0 }, depends_on:[], overlaps:[], agent:null, exit_criteria:['Symbol map uploads on every build','Crash keys wired for ARM32','Clean baseline dump captured'], workstreams:[ { key:'ws-recon-symbols', name:'Symbol Pipeline', description:'Symbol upload + crash keys for arm32.', file:'build/symbols/arm32.map', agent:'Cipher', slugs:['baseline-symbol-map'], progress:100 } ] },
    { key:'toolchain', name:'Toolchain & ARM32 Build', tagline:'Make it compile fast', goal:'PGO ARM32 build with NEON enabled tree-wide.', color:C.violet, icon:'ph-wrench', status:'done', pct:100, ordinal:1, rollup:{ total:1, done:1, open_crit_high:0 }, depends_on:['recon'], overlaps:[], agent:null, exit_criteria:['NEON codegen verified in objdump','PGO profile builds green','Link time under budget'], workstreams:[ { key:'ws-tc-neon', name:'NEON Codegen', description:'Propagate -mfpu=neon to all targets.', file:'build/config/arm.gni', agent:'Cipher', slugs:['toolchain-neon-flag-missing'], progress:100 } ] },
    { key:'boot', name:'Cold Boot & Renderer', tagline:'First pixels', goal:'Get browser + renderer to first paint on device.', color:C.blue, icon:'ph-power', status:'active', pct:62, ordinal:2, rollup:{ total:4, done:2, open_crit_high:1 }, depends_on:['toolchain'], overlaps:['gpu'], agent:'Vector', exit_criteria:['Renderer survives first GC','HTTPS to TLS1.3 hosts','No white flash on cold boot'], workstreams:[ { key:'ws-boot-v8', name:'V8 Bringup', description:'ARM/Thumb interworking + deopt stability.', file:'v8/src/codegen/arm/', agent:'Vector', slugs:['v8-thumb-interwork-crash'], progress:40 }, { key:'ws-boot-net', name:'Net Stack', description:'TLS + Mojo IPC correctness on 32-bit.', file:'net/,mojo/', agent:'Vector', slugs:['tls13-schannel-handshake','mojo-ipc-32b-offset'], progress:75 } ] },
    { key:'gpu', name:'GPU / Tegra 4 Pipeline', tagline:'Light up the GPU', goal:'Stable Tegra 4 compositor + NEON media/skia.', color:C.green, icon:'ph-cpu', status:'active', pct:30, ordinal:3, rollup:{ total:4, done:0, open_crit_high:3 }, depends_on:['boot'], overlaps:['boot'], agent:'Prism', exit_criteria:['No context loss on backgrounding','Gradient banding gone','WebGL2 sites render'], workstreams:[ { key:'ws-gpu-context', name:'Context Robustness', description:'Handle Tegra EGL context loss.', file:'gpu/command_buffer/', agent:'Prism', slugs:['tegra-gl-context-loss'], progress:20 }, { key:'ws-gpu-neon', name:'NEON Raster & Media', description:'Skia + FFmpeg NEON correctness.', file:'skia/,third_party/ffmpeg/', agent:'Prism', slugs:['skia-neon-alpha-banding','ffmpeg-neon-h264-artifact','angle-d3d9-shader-fallback'], progress:35 } ] },
    { key:'perf', name:'Perf & Memory Hotpaths', tagline:'Make it usable', goal:'Fit in 2GB VA and keep scroll smooth on A15.', color:C.orange, icon:'ph-gauge', status:'active', pct:35, ordinal:4, rollup:{ total:4, done:1, open_crit_high:2 }, depends_on:['boot'], overlaps:['stability'], agent:'Torque', exit_criteria:['No OOM under 1.4GB RSS','GC pauses under 30ms','Companion core utilized'], workstreams:[ { key:'ws-perf-mem', name:'Memory Fit', description:'PartitionAlloc under 2GB user VA.', file:'base/allocator/', agent:'Torque', slugs:['partition-alloc-oom-2g'], progress:30 }, { key:'ws-perf-v8', name:'V8 Latency', description:'GC pauses + icache flush.', file:'v8/src/heap/', agent:'Torque', slugs:['gc-pause-spike-scroll','v8-jit-cache-flush-miss','thread-affinity-tegra4'], progress:45 } ] },
    { key:'stability', name:'Crash Triage & Stability', tagline:'Stop the crashes', goal:'Drive top device crashers + leaks to zero.', color:C.red, icon:'ph-shield-check', status:'blocked', pct:15, ordinal:5, rollup:{ total:3, done:0, open_crit_high:2 }, depends_on:['gpu','perf'], overlaps:['perf'], agent:'Rescue', exit_criteria:['Cache survives power loss','No PAC-induced freezes','No handle leaks over 8h soak'], workstreams:[ { key:'ws-stab-cache', name:'Cache Integrity', description:'Atomic disk-cache index writes.', file:'net/disk_cache/', agent:'Rescue', slugs:['disk-cache-index-corrupt'], progress:15 }, { key:'ws-stab-net', name:'Net Resilience', description:'PAC time-boxing + handle hygiene.', file:'net/,mojo/', agent:'Rescue', slugs:['net-proxy-resolver-hang','mojo-handle-leak'], progress:20 } ] },
    { key:'polish', name:'Compat & Ship Polish', tagline:'Ship it', goal:'Compat shims, security pass, and visual polish.', color:C.fuchsia, icon:'ph-magic-wand', status:'pending', pct:8, ordinal:6, rollup:{ total:5, done:1, open_crit_high:0 }, depends_on:['stability'], overlaps:[], agent:null, exit_criteria:['Sandbox tightened for 8.1','No tofu / DPI blur','Dead flags removed'], workstreams:[ { key:'ws-polish-sec', name:'Security Pass', description:'Sandbox token audit for 8.1.', file:'sandbox/win/', agent:null, slugs:['sandbox-win81-token'], progress:10 }, { key:'ws-polish-ui', name:'Visual & Compat', description:'DPI, fonts, DRM, dead flags.', file:'ui/,components/cdm/', agent:null, slugs:['views-dpi-scale-blur','font-fallback-cjk-missing','media-eme-widevine-stub','dead-flag-legacy-gpu'], progress:12 } ] },
  ];

  // ===================== LIVE AGENTS (4 working) =====================
  const agents = [
    { name:'Vector', display:'Vector', color:C.blue,   status:'working', phase_key:'boot',      workstream_key:'ws-boot-v8',     activity:'Rebuilding interworking veneer + re-running deopt repro', progress:40, finding_slug:'v8-thumb-interwork-crash', last_heartbeat:ago(0.3) },
    { name:'Prism',  display:'Prism',  color:C.green,  status:'working', phase_key:'gpu',       workstream_key:'ws-gpu-neon',    activity:'Diffing NEON vs C blitter on gradient test page', progress:35, finding_slug:'skia-neon-alpha-banding', last_heartbeat:ago(0.6) },
    { name:'Torque', display:'Torque', color:C.orange, status:'working', phase_key:'perf',      workstream_key:'ws-perf-mem',    activity:'Profiling PartitionAlloc super-page fragmentation', progress:30, finding_slug:'partition-alloc-oom-2g', last_heartbeat:ago(1.2) },
    { name:'Rescue', display:'Rescue', color:C.red,    status:'working', phase_key:'stability', workstream_key:'ws-stab-cache',  activity:'Reproducing disk-cache index corruption on power-cut', progress:15, finding_slug:'disk-cache-index-corrupt', last_heartbeat:ago(2.4) },
    // a terminal remnant that liveAgents filters out — proves the getter works
    { name:'Cipher', display:'Cipher', color:C.cyan,   status:'idle',    phase_key:'toolchain', workstream_key:'ws-tc-neon',     activity:'', progress:100, finding_slug:null, last_heartbeat:ago(5000) },
  ];

  // ===================== MISSIONS + live_state HUD =====================
  const glyph = (id, family, ok, label) => ({ id, family, ok, label });
  const missions = [
    { key:'M-1042', title:'Fix ARM/Thumb interworking crash', name:'v8-thumb-interwork-crash', status:'running', agent:'Vector', color:C.blue, model:'claude-opus-4-8', effort:'L', effort_band:'high', reasoning:'High', bulk_effort:'high', verify_effort:'xhigh', item_counts:{ done:3, total:7 }, item_total:7, dispatched_at:ago(52), started_at:ago(48), completed_at:null },
    { key:'M-1039', title:'Triage disk-cache index corruption', name:'disk-cache-index-corrupt', status:'debugging', agent:'Rescue', color:C.red, model:'claude-opus-4-8', effort:'L', effort_band:'high', reasoning:'High', bulk_effort:'high', verify_effort:'xhigh', item_counts:{ done:1, total:5 }, item_total:5, dispatched_at:ago(140), started_at:ago(132), completed_at:null },
    { key:'M-1031', title:'Enable BoringSSL for TLS 1.3 on ARM32', name:'tls13-schannel-handshake', status:'resolved', agent:'Cipher', color:C.cyan, model:'claude-sonnet-4-5', effort:'M', effort_band:'medium', reasoning:'Medium', bulk_effort:'medium', verify_effort:'high', item_counts:{ done:4, total:4 }, item_total:4, dispatched_at:ago(1400), started_at:ago(1392), completed_at:ago(1300) },
  ];
  const queue = [
    { slug:'tegra-gl-context-loss', title:'Tegra 4 GL context lost -> black compositor', severity:'critical', status:'open', effort:'XL' },
    { slug:'partition-alloc-oom-2g', title:'PartitionAlloc address-space exhaustion', severity:'high', status:'open', effort:'L' },
    { slug:'net-proxy-resolver-hang', title:'PAC proxy resolver hangs isolate', severity:'high', status:'open', effort:'M' },
    { slug:'ffmpeg-neon-h264-artifact', title:'FFmpeg NEON H.264 green macroblocks', severity:'high', status:'open', effort:'L' },
  ];
  // live_state keyed by mission key (consumed via ls(m.key))
  const missionState = {
    'M-1042': { lifecycle:'implementing', stage_history:['queued','planning','implementing'], worker_online:true, session_id:'sess_9f2a', model:'claude-opus-4-8', permission_mode:'acceptEdits', activity:'Patching interworking veneer in macro-assembler-arm.cc', items:{ done:3, total:7 }, bugs_found:1, blockers:[], files_changed:['v8/src/codegen/arm/macro-assembler-arm.cc','v8/src/codegen/arm/assembler-arm.cc','v8/test/cctest/test-assembler-arm.cc'], files_changed_count:3, triad:{ build:{ state:'pass', target:'out/arm32_pgo', ts:ago(6) }, deploy:{ state:'running', target:'Surface 2 RT', ts:ago(2) }, smoke:{ state:'idle', target:'device', ts:null } }, device:{ process_alive:true, last_fault:null, exception_code:null, dump_captured:false }, tools_recent:[ glyph('t1','read',true,'Read macro-assembler-arm.cc'), glyph('t2','edit',true,'Edit veneer emit'), glyph('t3','bash',true,'ninja -C out/arm32_pgo v8'), glyph('t4','surface',null,'Deploy to Surface 2 RT'), glyph('t5','tracker',true,'Update finding status') ], cost_usd:2.18, tokens:{ input:184320, output:26880, cache_read:512000 }, turns:14, duration_ms:2760000, retries:0, next_action:'Deploy build and run deopt smoke test', plan:{ steps:['Reproduce deopt fault','Emit interworking-safe veneer','Assert bit0 on BLX targets','Rebuild + deploy','Smoke test on device'], files:['v8/src/codegen/arm/macro-assembler-arm.cc'], risk:'Veneer size may exceed short-branch range in large functions' }, approval_pending:{ tool_name:'Bash', command:'ninja -C out/arm32_pgo chrome && deploy_surface2', gate_id:'gate_77' }, updated_at:ago(2) },
    'M-1039': { lifecycle:'debugging', stage_history:['queued','planning','implementing','building','deploying','smoke','debugging'], worker_online:true, session_id:'sess_4c81', model:'claude-opus-4-8', permission_mode:'default', activity:'Analyzing crash dump 0xC0000005 in simple_index_file.cc', items:{ done:1, total:5 }, bugs_found:2, blockers:['Waiting on power-cut repro rig to free up'], files_changed:['net/disk_cache/simple/simple_index_file.cc'], files_changed_count:1, triad:{ build:{ state:'pass', target:'out/arm32_pgo', ts:ago(40) }, deploy:{ state:'pass', target:'Surface 2 RT', ts:ago(30) }, smoke:{ state:'fail', target:'device', ts:ago(18) } }, device:{ process_alive:false, last_fault:'ACCESS_VIOLATION reading index page', exception_code:'0xC0000005', dump_captured:true }, tools_recent:[ glyph('u1','tracker',true,'Fetch finding'), glyph('u2','read',true,'Read simple_index_file.cc'), glyph('u3','bash',true,'build'), glyph('u4','surface',false,'Smoke test crashed'), glyph('u5','surface',true,'Capture crash dump') ], cost_usd:3.94, tokens:{ input:262144, output:41200, cache_read:768000 }, turns:22, duration_ms:7920000, retries:1, next_action:'Add atomic rename + CRC validation to index writer', plan:{ steps:['Symbolize dump','Locate unfsynced write','Add temp+rename','Validate CRC on load','Re-run power-cut soak'], files:['net/disk_cache/simple/simple_index_file.cc'], risk:'CRC check may reject legitimately-old indexes' }, approval_pending:null, updated_at:ago(4) },
    'M-1031': { lifecycle:'resolved', stage_history:['queued','planning','implementing','building','deploying','smoke','resolved'], worker_online:false, session_id:'sess_1a09', model:'claude-sonnet-4-5', permission_mode:'acceptEdits', activity:'Resolved — BoringSSL handshake verified', items:{ done:4, total:4 }, bugs_found:1, blockers:[], files_changed:['net/socket/ssl_client_socket_impl.cc','net/BUILD.gn'], files_changed_count:2, triad:{ build:{ state:'pass', target:'out/arm32_pgo', ts:ago(1340) }, deploy:{ state:'pass', target:'Surface 2 RT', ts:ago(1320) }, smoke:{ state:'pass', target:'device', ts:ago(1305) } }, device:{ process_alive:true, last_fault:null, exception_code:null, dump_captured:false }, tools_recent:[ glyph('v1','read',true,'Read ssl_client_socket_impl.cc'), glyph('v2','edit',true,'Force BoringSSL arm32'), glyph('v3','bash',true,'build'), glyph('v4','surface',true,'Smoke: TLS1.3 handshake OK'), glyph('v5','tracker',true,'Mark resolved') ], cost_usd:1.12, tokens:{ input:98000, output:14300, cache_read:210000 }, turns:9, duration_ms:5400000, retries:0, next_action:'', plan:null, approval_pending:null, updated_at:ago(1300) },
  };

  // ===================== EVENT STREAM =====================
  const events = [
    { id:5001, kind:'finding',    ref:'tegra-gl-context-loss', summary:'Severity raised high -> critical', ts:ago(60),  actor:'user',  severity:'critical' },
    { id:5000, kind:'heartbeat',  ref:'Vector', summary:'Vector heartbeat · implementing', ts:ago(0.3), actor:'agent', severity:null },
    { id:4999, kind:'workstream', ref:'ws-gpu-neon', summary:'Prism progress 35% on NEON raster', ts:ago(0.6), actor:'agent', severity:null },
    { id:4998, kind:'finding',    ref:'v8-thumb-interwork-crash', summary:'Reopened after deopt repro still faults', ts:ago(190), actor:'agent', severity:'critical' },
    { id:4997, kind:'comment',    ref:'partition-alloc-oom-2g', summary:'Torque: super-page reservation fragments at 1.4GB', ts:ago(240), actor:'agent', severity:'high' },
    { id:4996, kind:'phase',      ref:'stability', summary:'Phase marked blocked — awaiting repro rig', ts:ago(300), actor:'user', severity:null },
    { id:4995, kind:'finding',    ref:'skia-neon-alpha-banding', summary:'Moved open -> in_progress', ts:ago(95), actor:'agent', severity:'high' },
    { id:4994, kind:'finding',    ref:'disk-cache-index-corrupt', summary:'Crash dump 0xC0000005 captured', ts:ago(18), actor:'agent', severity:'critical' },
    { id:4993, kind:'agent',      ref:'Rescue', summary:'Rescue picked up disk-cache mission', ts:ago(132), actor:'agent', severity:null },
    { id:4992, kind:'finding',    ref:'thread-affinity-tegra4', summary:'Verified — 11% idle-power win', ts:ago(700), actor:'user', severity:'medium' },
    { id:4991, kind:'finding',    ref:'tls13-schannel-handshake', summary:'Resolved — BoringSSL forced for arm32', ts:ago(1300), actor:'agent', severity:'high' },
    { id:4990, kind:'workstream', ref:'ws-boot-net', summary:'Net stack workstream at 75%', ts:ago(1350), actor:'agent', severity:null },
  ];

  // ===================== NOTIFY (Home Assistant) =====================
  const notify = {
    enabled:true, base_url:'https://ha.local.lan', default_service:'notify.mobile_app_pixel',
    token_set:true, token_last4:'a91f', token_input:'', tokenEditing:false, saving:false, testing:false,
    rules:[
      { id:'rule-1', name:'Critical crashes -> phone', enabled:true, event_types:['blocked','api_error','stall'], service:'notify.mobile_app_pixel', title_template:'[{mission_key}] {status}', message_template:'{mission_title} — {reason}', channel:'crashes', importance:'high', priority:'high', ttl:'', persistent:true, sticky:false, tag:'arm32-crash', color:'#FF3B5C', actions:[{ title:'Open HUD', action:'URI', uri:'/#mission' }] },
      { id:'rule-2', name:'Approval gates', enabled:true, event_types:['question'], service:'notify.mobile_app_pixel', title_template:'Approval needed · {agent}', message_template:'{mission_title}: {tool_name} {command}', channel:'approvals', importance:'default', priority:'normal', ttl:'600', persistent:false, sticky:true, tag:'approval', color:'#FF9500', actions:[{ title:'Approve', action:'APPROVE', uri:'' },{ title:'Deny', action:'DENY', uri:'' }] },
      { id:'rule-3', name:'Mission resolved', enabled:false, event_types:['done','session_end'], service:'notify.mobile_app_pixel', title_template:'Resolved: {mission_title}', message_template:'{agent} finished {mission_key} in {phase}', channel:'done', importance:'low', priority:'normal', ttl:'', persistent:false, sticky:false, tag:'done', color:'#00FF95', actions:[] },
    ],
  };

  // ===================== CHART SERIES =====================
  const charts = {
    // line/area time-series — findings opened vs resolved per week (8 wks)
    findingsWeekly:[
      { week:'W23', opened:5, resolved:1 }, { week:'W24', opened:4, resolved:2 },
      { week:'W25', opened:6, resolved:3 }, { week:'W26', opened:3, resolved:2 },
      { week:'W27', opened:4, resolved:4 }, { week:'W28', opened:2, resolved:3 },
      { week:'W29', opened:3, resolved:5 }, { week:'W30', opened:2, resolved:2 },
    ],
    // burndown (remaining open vs ideal) for an optional 2nd line
    burndown:[
      { week:'W23', remaining:22, ideal:22 }, { week:'W24', remaining:20, ideal:19 },
      { week:'W25', remaining:20, ideal:16 }, { week:'W26', remaining:18, ideal:13 },
      { week:'W27', remaining:16, ideal:10 }, { week:'W28', remaining:15, ideal:7 },
      { week:'W29', remaining:14, ideal:4 }, { week:'W30', remaining:14, ideal:1 },
    ],
    // doughnut — severity mix (matches stats.by_severity)
    severity:[
      { label:'Critical', value:3, color:C.red },    { label:'High', value:8, color:C.orange },
      { label:'Medium', value:6, color:C.yellow },   { label:'Low', value:3, color:C.cyan },
      { label:'Cleanup', value:2, color:C.dim },
    ],
    // bar — findings per subsystem (matches stats.by_subsystem)
    subsystem:[
      { label:'v8-arm', value:4, color:C.cyan },       { label:'net-tls', value:2, color:C.blue },
      { label:'skia-neon', value:2, color:C.green },    { label:'ipc-mojo', value:2, color:C.violet },
      { label:'ui-views', value:2, color:C.fuchsia },   { label:'media-ffmpeg', value:2, color:C.orange },
      { label:'base-threading', value:2, color:C.yellow }, { label:'gl-angle', value:2, color:C.red },
      { label:'gpu-tegra', value:1, color:C.cyan },     { label:'mem-partition', value:1, color:C.blue },
      { label:'storage-disk-cache', value:1, color:C.green }, { label:'sandbox-win', value:1, color:C.violet },
    ],
    // histogram — effort distribution (S/M/L/XL)
    effort:[
      { label:'S', value:6, color:C.cyan }, { label:'M', value:9, color:C.blue },
      { label:'L', value:6, color:C.violet }, { label:'XL', value:1, color:C.fuchsia },
    ],
    // histogram — age of open findings (buckets)
    age:[
      { label:'<1d', value:3, color:C.green }, { label:'1-3d', value:4, color:C.cyan },
      { label:'3-7d', value:3, color:C.yellow }, { label:'1-2w', value:2, color:C.orange },
      { label:'>2w', value:2, color:C.red },
    ],
    // KPI tiles (Analytics headline row — each backs a sparkline canvas kpi-<key>-spark)
    kpis:[
      { key:'total',    label:'Total Findings',    value:22, delta:'+3 this wk', color:C.cyan,   icon:'ph-list',
        spark:[16,17,18,18,19,20,20,21,21,22,22,22] },
      { key:'open',     label:'Open / Active',     value:14, delta:'-2 this wk', color:C.orange, icon:'ph-circle',
        spark:[18,18,17,17,16,16,15,15,14,14,14,14] },
      { key:'crit',     label:'Crit + High Open',  value:8,  delta:'+1 this wk', color:C.red,    icon:'ph-warning-octagon',
        spark:[5,6,6,7,7,7,8,8,7,8,8,8] },
      { key:'progress', label:'Overall Progress',  value:27, unit:'%', delta:'+6% this wk', color:C.green, icon:'ph-gauge',
        spark:[8,10,12,14,15,18,20,22,24,25,26,27] },
    ],
  };

  return { NOW, colors:C, stats, findings, phases, agents, missions, queue, missionState, events, notify, charts };
})();
